spring:
  application:
    name: mini-erp
  flyway:
    clean-disabled: true
    default-schema: mini_erp
    enabled: true
    locations: classpath:db/migration
    schemas: mini_erp
    validate-migration-naming: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: mini_erp
        jdbc:
          time_zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
